### PR TITLE
Check TPP and XSMM element types

### LINKED ISSUE #743: tpp.zero error: 'tpp.zero' op operand #0 must be 1D/2D memref of floating-point values or 1D/2D tensor of floating-point values or floating-point, but got 'tensor<>'
Running [attached BERT model](https://github.com/plaidml/tpp-mlir/files/12920055/bert1.mlir.txt) fails with error in `tpp.zero`.

*TPP-MLIR commit*
`ac505bedba95c56c0e7aa5adc93824509270792b`

*Reproducer*

```
$ tpp-opt -default-tpp-passes bert1.mlir.txt

bert1.mlir:244:11: error: 'tpp.zero' op operand #0 must be 1D/2D memref of floating-point values or 1D/2D tensor of floating-point values or floating-point, but got 'tensor<12x8xi64>'
    %51 = linalg.fill ins(%c0_i64 : i64) outs(%50 : tensor<1x12x8x1xi64>) -> tensor<1x12x8x1xi64>
          ^
bert1.mlir:244:11: note: see current operation: %87 = "tpp.zero"(%86) <{operandSegmentSizes = array<i32: 1, 0>}> : (tensor<12x8xi64>) -> tensor<12x8xi64>
```

### PR DESCRIPTION
**Pull request by adam-smnk**
Adds operand element type checking to TPP and XSMM operation matcher.

Removes XSMM assert for better debug quality - it lets operation verifier return readable and traceable error.

Fixes #743

### CODE REVIEW

File: include/TPP/IR/StructuredOpMatcher.h [hunk 1]
```diff
@@ -183,6 +183,16 @@ struct HasRank {
   std::vector<int64_t> ranks;
 };
 
+// Callable object to verify `operand` to have an element type `T`.
+template <typename T> struct HasElementType {
+  bool operator()(OpOperand *operand, Operation *op) const {
+    auto operandType = operand->get().getType();
```
Comment (chelini) [inline include/TPP/IR/StructuredOpMatcher.h:189]: `getElementTypeOrSelf`?

File: lib/TPP/ConvertLinalgToTpp.cpp [hunk 2]
```diff
@@ -114,9 +114,14 @@ struct ConvertBrgemmToTpp
     }
     SmallVector<Value> inputs = brMatmulOp.getDpsInputs();
     inputs.push_back(brMatmulOp.getDpsInits()[0]);
-    SmallVector<Value> outputs = brMatmulOp.getDpsInits();
-    rewriter.replaceOpWithNewOp<tpp::BrgemmOp>(brMatmulOp, inputs,
-                                               outputs[0].getType());
+    Value output = brMatmulOp.getDpsInits()[0];
+    auto outType = dyn_cast_or_null<ShapedType>(output.getType());
```
Comment (chelini) [inline lib/TPP/ConvertLinalgToTpp.cpp:118]: I think: dyn_cast only is enough. outputType should be non null;

**Review by chelini — APPROVED** [review]
thx.
